version: "3.1"

services:
    api:
        container_name: api
        build: .
        env_file:
            - .env
        command: ["npx", "nodemon", "./index.ts"]
        ports:
            - "8080:8080"

        volumes:
            - .:/api
        networks:
            - app-network

    web:
        image: nginx
        container_name: web
        volumes:
            - ./volumes/nginx/templates:/etc/nginx/templates
            - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./volumes/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "9090:80"
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80
        networks:
            - app-network
        depends_on:
            - api
    mongo:
        image: mongo:4.4.9-focal
        container_name: mongo
        restart: always
        env_file:
            - .env
        volumes:
            - ./volumes/db:/data/db
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: API
networks:
    app-network:
        driver: bridge
