version: '3.1'

services:

  mongo:
    image: mongo:4.4.9-focal
    restart: always
    env_file:
      - .env
    volumes:
      - ./volumes/db:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: API
  api:
    build: .
    env_file:
      - .env
    command: ["npx", "nodemon", "./index.ts"]
    ports:
      - "8080:8080"

    volumes:
      - .:/api
